aws_profile                 = "terraform_2599" 
aws_region                  = "us-east-2"
aws_env                     = "dev"
app_name                    = "CFFunctionDemo"
app_shortcode               = "cffd"
apigw_stage_name            = "api"
lambda_function_name        = "EchoLambda"
lambda_api_name             = "echo"