'use strict'

function handler(event) {
  var request = event.request;
  var response  = event.response;

  var secondsSinceEpoch = Math.round(Date.now() / 1000); 

  var traceId; 
  var cfId = request.headers['x-amz-cf-id']; 
  if (cfId && cfId.length >= 24)  {
    // if x-amz-cf-id header is present, copy over value to x-amzn-trace-id header
    // currently, cloudfront doesn't create x-amz-cf-id request header by when this function is called 
    // field value must be 'Root', using 'Self' does not seem to work currently
    traceId = 'Root=1-' + secondsSinceEpoch.toString(16).substring(0, 8) + '-' + cfId.substring(0, 24); 
  } else {
    traceId = 'Root=1-' + secondsSinceEpoch.toString(16).substring(0, 8) + '-' + genHexString(24); 
  }

  request.headers['x-amzn-trace-id'] = { value: traceId };
  request.headers['cf-function'] = { value: 'generated by cloudfront function (trace-id: ' + traceId +')' };
  return request;

  // uncomment this and comment above lines if trace id header must be returned in viewer response instead
  //response.headers['x-amzn-trace-id'] = { value: traceId };
  //return response; 
}

function genHexString(len) {
  var hex = '0123456789abcdef';
  var output = '';
  for (var i = 0; i < len; ++i) {
      output += hex.charAt(Math.floor(Math.random() * 16));
  }
  return output;
}
